### ISSUE TITLE
dbManga in MangaController.js cannot find MangaName

### ISSUE THREAD

**Issue by ndao335** [rwxlucas/manga-reader#1]
I got an error when trying to run the frontend. I already started the backend. Do I need to store mangas in the database or keep all mangas in the ../backend/mangas folder?

![Screen Shot 2021-06-12 at 2 42 08 PM](https://user-images.githubusercontent.com/78671480/121789647-5fea9080-cb8c-11eb-8871-6b5400bacc10.png)

**Comment by rwxlucas** [comment]
Hello! This was my first project... I made to have a folder with the
mangas, I did not store in database. I had no idea that someone would see
my project! Ahahaha. But that's it, you have to have the mangas on one
folder.

**Comment by ndao335** [comment]
> Hello! This was my first project... I made to have a folder with the mangas, I did not store in database. I had no idea that someone would see my project! Ahahaha. But that's it, you have to have the mangas on one folder.
> […](#)

Hello Lucas, I like your project. It is very interesting and has a lot of potential and room to improve. But when I ran “npm start” on backend and frontend while mongodb is running in the terminal for user account, i ran into the error as shown in the image above. Have you run across that issue before?
